### ISSUE TITLE
Add default Metrics endpoint

### ISSUE THREAD

**Issue by gtokman** [MykalMachon/railway-grafana-stack#11]
I'm seeing traces and logs now, thanks!

Re. Metrics, can we add a default path to the `prom.yml` like GET `/metrics` and as along as it's specified then Prometheus pulls it? Otherwise users of the stack can fork it and add their own. 

> As far as metrics go, if you're hoping to use prometheus you will have to fork this repo and alter the prometheus/prom.yml file to pull from your metrics endpoints. Since prometheus is pull based unfortunately that's the only option 😄

**Comment by gtokman** [comment]
I see why you mentioned that I'd need to fork it bc the domain is custom, right?

```
global:
  scrape_interval: 15s # Default scrape interval

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "api"
    scheme: https
    static_configs:
      - targets: ["myapi.com"]

```
